library(data.table)
library(dplyr)
library(lubridate)
library(stringr)

#load data
userdata_1k <- fread("../../data/userdata_1k.csv")

#remove columns 
userdata_1k <- userdata_1k[, -1]

###################
#DATE MANIPULATION#
###################

# timestamp to dates
userdata_1k$date <- as.Date(userdata_1k$timestamp)

# dates to total time timestamps
userdata_1k <- userdata_1k %>% group_by(userid) %>% mutate(total_days = max(date)-min(date))

# days numeric
userdata_1k$total_days_num <- as.numeric(userdata_1k$total_days, unit = "days")

# months numeric
userdata_1k$months <- time_length(userdata_1k$total_days, unit = "months")

# rearrange colums
userdata_1k <- userdata_1k[, c(1, 2, 7:10, 3:6)]

#################
#FILTER 1 MONTHS#
#################

userdata_1k_1month <- userdata_1k %>% filter(months >= 1)

#####################
#DETERMINE DATERANGE#
#####################

# check for users with 1 months total listening time
users_1m <- userdata_1k_1month %>% filter(months < 2)
users_1m <- users_1m %>% group_by(userid) %>% mutate(mindate = min(date))
users_1m <- users_1m %>% group_by(userid) %>% mutate(maxdate = max(date))

table(users_1m$mindate)
table(users_1m$maxdate)
# So, the minimum dates are ranging all in the March 2009. Max dates are all in May 2009, except one who is in the end of April 2009. 
# Conclusion: dataset in April 2009 as this is a month where all have listened

# remove dataset for clean environment
rm(users_1m, userdata_1k_1month)

##################
#FILTER DATERANGE#
##################

users_1month <- userdata_1k %>% filter(date >= "2009-04-01" & date <= "2009-04-30")

###############
#CLEAN ARTISTS#
###############

users_1month$artist <- str_replace_all(users_1month$artist, "[:digit:][:digit:]\\. Kaliyuga Pro.", "Kaliyuga Pro.")
users_1month$artist <- str_replace_all(users_1month$artist, ",  Melodie", "")
users_1month$artist <- str_replace_all(users_1month$artist, "/Melodie", "")
users_1month$artist <- str_replace_all(users_1month$artist, "- Ost Cd 1", "")
users_1month$artist <- str_replace_all(users_1month$artist, "- Ost Cd 2", "")
users_1month$artist <- str_replace_all(users_1month$artist, "2paq", "2pac")
users_1month$artist <- str_replace_all(users_1month$artist, "8 Mile Soundtrack - ", "")
users_1month$artist <- str_replace_all(users_1month$artist, "Act One", "Act 1")
users_1month$artist <- str_replace_all(users_1month$artist, " \\(1988\\)", "")
users_1month$artist <- str_replace_all(users_1month$artist, "Afro Menduesa", "Afro Medusa")
users_1month$artist <- str_replace_all(users_1month$artist, "0Akon", "Akon")
users_1month$artist <- str_replace_all(users_1month$artist, "Akon Feat Lil Wayne", "Akon")
users_1month$artist <- str_replace_all(users_1month$artist, "Akon Ft. Lil Wayne", "Akon")
users_1month$artist <- str_replace_all(users_1month$artist, "Akon Featuring Eminem", "Akon")
users_1month$artist <- str_replace_all(users_1month$artist, "Akon Feat Colby O'Donis & Kardinal Offishall", "Akon")
users_1month$artist <- str_replace_all(users_1month$artist, "Albert King With Stevie Ray Vaughan", "Albert King")
users_1month$artist <- str_replace_all(users_1month$artist, "Albert King & Otis Rush", "Albert King")
users_1month$artist <- str_replace_all(users_1month$artist, "Alex Gaudino Feat. Shena", "Alex Gaudino")
users_1month$artist <- str_replace_all(users_1month$artist, "Alex Gaudino & Jerma Present Lil' Love", "Alex Gaudino")
users_1month$artist <- str_replace_all(users_1month$artist, "Ali Farka Touré With Ry Cooder", "Ali Farka Touré")
users_1month$artist <- str_replace_all(users_1month$artist, "Ali Farka Touré & Toumani Diabaté", "Ali Farka Touré")
users_1month$artist <- str_replace_all(users_1month$artist, "Allen Ginsberg / Illyb", "Allen Ginsberg")
users_1month$artist <- str_replace_all(users_1month$artist, "\\bAllison Crowe\\b", "Allison Crowe (Holiday)")
users_1month$artist <- str_replace_all(users_1month$artist, "\\(Holiday\\) \\(Holiday\\)", "(Holiday)")
users_1month$artist <- str_replace_all(users_1month$artist, "Alozade And Hollow Point", "Alozade")
users_1month$artist <- str_replace_all(users_1month$artist, "Alpha Beat", "Alphabeat")
users_1month$artist <- str_replace_all(users_1month$artist, "Altamiro Carrilho & Ronaldo Do Bandolim", "Altamiro Carrilho")
users_1month$artist <- str_replace_all(users_1month$artist, "Alva Noto \\+ Ryuichi Sakamoto", "Alva Noto")
users_1month$artist <- str_replace_all(users_1month$artist, "Alva Noto \\+ Opiate", "Alva Noto")
users_1month$artist <- str_replace_all(users_1month$artist, "Amanda Seyfried, Ashley Lilley And Rachel Mcdowall", "Amanda Seyfried")
users_1month$artist <- str_replace_all(users_1month$artist, "Amanda Seyfried/Dominic Cooper", "Amanda Seyfried")
users_1month$artist <- str_replace_all(users_1month$artist, "Dominic Cooper And Amanda Seyfried", "Amanda Seyfried")
users_1month$artist <- str_replace_all(users_1month$artist, "Amel Larrieux, Glenn Lewis, Stanley Clarke", "Amel Larrieux")
users_1month$artist <- str_replace_all(users_1month$artist, "Amerie Feat.  Fabolous", "Amerie")
users_1month$artist <- str_replace_all(users_1month$artist, "Amilcare Poncielli", "Amilcare Ponchielli")
users_1month$artist <- str_replace_all(users_1month$artist, "Andrea Demirović", "Andrea Demirovic")
users_1month$artist <- str_replace_all(users_1month$artist, "Andrew Spencer Vs. Lazard", "Andrew Spencer")
users_1month$artist <- str_replace_all(users_1month$artist, "Andrew W.K. & B-Roc", "Andrew W.K.")
users_1month$artist <- str_replace_all(users_1month$artist, "Andy Hunter", "Andy Hunter°")
users_1month$artist <- str_replace_all(users_1month$artist, "°°", "°")
users_1month$artist <- str_replace_all(users_1month$artist, "Andy Sheppard & Naná Vasconcelos", "Andy Sheppard")
users_1month$artist <- str_replace_all(users_1month$artist, "Angelo Badalamenti \\- Laura'S Theme \\(Instrumental\\)", "Angelo Badalamenti")
users_1month$artist <- str_replace_all(users_1month$artist, "Anna Maria Jopek \\+ Tomasz Stanko", "Anna Maria Jopek") 
users_1month$artist <- str_replace_all(users_1month$artist, "Antoine Clamaran Feat. Emily Chick\\[Www.Zabawa.Org\\]", "Antoine Clamaran")
users_1month$artist <- str_replace_all(users_1month$artist, "Antoine Clamaran \\& Emily Chick", "Antoine Clamaran")
users_1month$artist <- str_replace_all(users_1month$artist, "Apocalyptica Feat Three Days Grace", "Apocalyptica")
users_1month$artist <- str_replace_all(users_1month$artist, "Apocalyptica Feat. A. Gontier", "Apocalyptica")
users_1month$artist <- str_replace_all(users_1month$artist, "Armin Van Buuren \\(Feat. Sharon Den Adel\\)", "Armin Van Buuren")
users_1month$artist <- str_replace_all(users_1month$artist, "Armin Van Buuren \\& Dj Shah \\(Feat. Chris Jones\\)", "Armin Van Buuren")
users_1month$artist <- str_replace_all(users_1month$artist, "Armin Van Buuren Feat. Sharon Den Adel", "Armin Van Buuren")
users_1month$artist <- str_replace_all(users_1month$artist, "Armin Van Buuren F. Ray Wilson", "Armin Van Buuren")
users_1month$artist <- str_replace_all(users_1month$artist, "Armin Van Buuren Feat. Jan Vayne", "Armin Van Buuren")
users_1month$artist <- str_replace_all(users_1month$artist, "Armin Van Buuren Featuring Ray Wilson", "Armin Van Buuren")
users_1month$artist <- str_replace_all(users_1month$artist, "Axwell \\(By \\@Ello\\-\\)", "Axwell")
users_1month$artist <- str_replace_all(users_1month$artist, "Axwell Vs. Kanye West", "Axwell")
users_1month$artist <- str_replace_all(users_1month$artist, "Az Rotator", "Az-Rotator")
users_1month$artist <- str_replace_all(users_1month$artist, "Baden Powell-Charlie Byrd-Joao Gilberto", "Baden Powell\\/Charlie Byrd\\/Joao Gilberto")
users_1month$artist <- str_replace_all(users_1month$artist, "Beat Konducta \\(Aka Madlib\\)", "Beat Konducta")
users_1month$artist <- str_replace_all(users_1month$artist, "Beyoncй", "Beyoncé")
users_1month$artist <- str_replace_all(users_1month$artist, "Birdman \\& Lil' Wayne", "Birdman \\& Lil Wayne")
users_1month$artist <- str_replace_all(users_1month$artist, "Bmx Bandits \\[With Yeon Gene\\]", "Bmx Bandits")
users_1month$artist <- str_replace_all(users_1month$artist, "Booker T. \\& The Mgs \\- Green Onions", "Booker T. \\& The Mgs")
users_1month$artist <- str_replace_all(users_1month$artist, "Booker T. \\& The Mg'S", "Booker T. \\& The Mgs")
users_1month$artist <- str_replace_all(users_1month$artist, "Bournemouth Symphony Orchestra\\/Bournemouth Symphony Orchestra", "Bournemouth Symphony Orchestra")
users_1month$artist <- str_replace_all(users_1month$artist, "Brandy \\-\\[Emb\\]\\-", "Brandy")
users_1month$artist <- str_replace_all(users_1month$artist, "Bruce Hornsby Feat. Sting", "Bruce Hornsby & Sting")
users_1month$artist <- str_replace_all(users_1month$artist, "Buck 65 Remix \\(Featuring Sufjan Stevens And Serengeti\\)", "Buck 65")
users_1month$artist <- str_replace_all(users_1month$artist, "Buck 65 Remix \\(Featuring Sufjan Stevens\\)", "Buck 65")
users_1month$artist <- str_replace_all(users_1month$artist, "Buck 65, Sufjan Stevens And Serengeti", "Buck 65")
users_1month$artist <- str_replace_all(users_1month$artist, "Butti 49", "Butti-49")
users_1month$artist <- str_replace_all(users_1month$artist, "Carter Burwell\\/Various Artist", "Carter Burwell") 
users_1month$artist <- str_replace_all(users_1month$artist, "Cavaleiros Do Zodíaco", "Cavaleiros Do Zodiaco")
users_1month$artist <- str_replace_all(users_1month$artist, "Www.Cavaleiroszodiaco.Com.Br", "Cavaleiros Do Zodiaco")
users_1month$artist <- str_replace_all(users_1month$artist, "Os Cavaleiros Do Zodiaco", "Cavaleiros Do Zodiaco")
users_1month$artist <- str_replace_all(users_1month$artist, "Centro\\-Matic South San Gabriele", "Cavaleiros Do Zodiaco") #south san gabriele is an album of cavaleiros do Zodiaco
users_1month$artist <- str_replace_all(users_1month$artist, "Cevin Fisher Feat. Loletta Holloway", "Cevin Fisher Feat. Loleatta Holloway")
users_1month$artist <- str_replace_all(users_1month$artist, "Chick Corea Elektric Band Ii", "Chick Corea Elektric Band")
users_1month$artist <- str_replace_all(users_1month$artist, "Chris Montana Pres Bora Bora C", "Chris Montana Pres Bora Bora Chicks")
users_1month$artist <- str_replace_all(users_1month$artist, "Chris Tomlin, Martin Smith, Kirk Franklin And Watoto Children'S Choir", "Chris Tomlin")
users_1month$artist <- str_replace_all(users_1month$artist, "Christian Prommer'S Drum Lesson", "Christian Prommer'S Drumlesson")
users_1month$artist <- str_replace_all(users_1month$artist, "Christina Aguilera, Mya, Pink, Lil Kim", "Christina Aguilera, Mya, Pink \\& Lil' Kim")
users_1month$artist <- str_replace_all(users_1month$artist, "Christina Aguilera, Lil' Kim, Mýa \\& P!Nk", "Christina Aguilera, Mya, Pink \\& Lil' Kim")
users_1month$artist <- str_replace_all(users_1month$artist, "Ciara Featuring Justin Timberlake", "Ciara Ft. Justin Timberlake")
users_1month$artist <- str_replace_all(users_1month$artist, "Ciara Feat Justin Timberlake", "Ciara Ft. Justin Timberlake")
users_1month$artist <- str_replace_all(users_1month$artist, "Cloud Cult \\- The Ghost Inside Our House", "Cloud Cult") # song of Cloud Cult
users_1month$artist <- str_replace_all(users_1month$artist, "Coco Tea", "Cocoa Tea")
users_1month$artist <- str_replace_all(users_1month$artist, "Code Geass Lelouch Of The Rebellion O.S.T. 2", "Code Geass Lelouch Of The Rebellion O.S.T.")
users_1month$artist <- str_replace_all(users_1month$artist, "Code Geass Lelouch Of The Rebellion R2 O.S.T. 2", "Code Geass Lelouch Of The Rebellion O.S.T.")
users_1month$artist <- str_replace_all(users_1month$artist, "Code Geass Lelouch Of The Rebellion R2 O.S.T. 1", "Code Geass Lelouch Of The Rebellion O.S.T.")
users_1month$artist <- str_replace_all(users_1month$artist, "Cold \\(Metal\\)", "Cold")
users_1month$artist <- str_replace_all(users_1month$artist, "Coldplay \\+ Weezer \\+ Cut Copy \\+ The Blow \\+ M.I.A. \\+ Reading Rainbow", "Coldplay")
users_1month$artist <- str_replace_all(users_1month$artist, "Cut Chemist Meets Shortkut", "Cut Chemist\\/Shortcut")
users_1month$artist <- str_replace_all(users_1month$artist, "Daddy Dj \\- Let Your Body Talk", "Daddy Dj")
users_1month$artist <- str_replace_all(users_1month$artist, "Daft Punk Vs. U2", "Daft Punk")
users_1month$artist <- str_replace_all(users_1month$artist, "Daft Punk Vs B.Benassi", "Daft Punk")
users_1month$artist <- str_replace_all(users_1month$artist, "Dahlbäck, Diaz, Young Rebels \\& Terri B", "Dahlbäck, Diaz \\& Young Rebels Ft. Terri B\\!")
users_1month$artist <- str_replace_all(users_1month$artist, "Dahlbäck, Diaz \\& Young Rebels Feat. Terri B\\!", "Dahlbäck, Diaz \\& Young Rebels Ft. Terri B\\!")
users_1month$artist <- str_replace_all(users_1month$artist, "Damien Jurado \\& Gathered In Song", "Damien Jurado")
users_1month$artist <- str_replace_all(users_1month$artist, "Damien Rice \\- B\\-Sides", "Damien Rice")
users_1month$artist <- str_replace_all(users_1month$artist, "Dana Fuchs, Evan Rachel Wood, Jim Sturgess, Joe Anderson \\& T.V. Carpio", "Dana Fuchs, Jim Sturgess, Evan Rachel Wood And T. V. Carpio")
users_1month$artist <- str_replace_all(users_1month$artist, "Danny Dove \\& Steve Smart Ft Amanda Wilson", "Danny Dove \\& Steve Smart \\(Feat. Amanda Wilson\\)")
users_1month$artist <- str_replace_all(users_1month$artist, "Darude Feat. Blake Lewis", "Darude Ft. Blake Lewis")
users_1month$artist <- str_replace_all(users_1month$artist, "Dave Aude \\& Tall Paul Featuring Sisely Treasure", "Dave Aude \\& Tall Paul Ft. Sisely Treasure")
users_1month$artist <- str_replace_all(users_1month$artist, "Dave Dean 'S Musical Forklift", "Dave Dean'S Musical Forklift")
users_1month$artist <- str_replace_all(users_1month$artist, "David Carradine, Julie Dreyfus And Uma Thurman", "Uma Thurman, David Carradine \\& Julie Dreyfus")
users_1month$artist <- str_replace_all(users_1month$artist, "David Guetta, Steve Angello, Joachim Garraud, Sebastian Ingrosso, Chris Willis", "David Guetta")
users_1month$artist <- str_replace_all(users_1month$artist, "David Morales Presents The Face Ft. Juliet Roberts", "David Morales")
users_1month$artist <- str_replace_all(users_1month$artist, "David Morales Feat. Lea\\-Lorien", "David Morales")
users_1month$artist <- str_replace_all(users_1month$artist, "David Sylvian, Ryuichi Sakamoto, Amadeo Pace, Keigo Oyamada \\& Sketch Show", "David Sylvian")
users_1month$artist <- str_replace_all(users_1month$artist, "David Torn, Tim Berne, Craig Taborn, Tom Rainey", "David Torn")
users_1month$artist <- str_replace_all(users_1month$artist, "David Vandervelde \\- Hit The Road", "David Vandervelde")
users_1month$artist <- str_replace_all(users_1month$artist, "Daz\\-I\\-Kue", "Daz\\-I\\-Cue")
users_1month$artist <- str_replace_all(users_1month$artist, "Db Boulebard", "Db Boulevard")
users_1month$artist <- str_replace_all(users_1month$artist, "Dean Martin, Frank Sinatra, Sa", "Dean Martin \\& Frank Sinatra")
users_1month$artist <- str_replace_all(users_1month$artist, "Dear Nora \\& Casiotone For The Painfully Alone", "Dear Nora")
users_1month$artist <- str_replace_all(users_1month$artist, "Death Note Ost I", "Death Note")
users_1month$artist <- str_replace_all(users_1month$artist, "Death Note Ost Ii", "Death Note")
users_1month$artist <- str_replace_all(users_1month$artist, "Death Note Ost Iii", "Death Note")
users_1month$artist <- str_replace_all(users_1month$artist, "Del The Funky Homosapien", "Del Tha Funkee Homosapien\\/Gorillaz")
users_1month$artist <- str_replace_all(users_1month$artist, "Delinquent \\& Kcat", "Delinquent \\(Feat. Kcat\\)")
users_1month$artist <- str_replace_all(users_1month$artist, "Delly Ranx", "Delly Ranks")
users_1month$artist <- str_replace_all(users_1month$artist, "Demarco\\- When The Love A Come Down", "Demarco")
users_1month$artist <- str_replace_all(users_1month$artist, "Detroit Grand Pubahs\\/New Order", "Detroit Grand Pubahs")
users_1month$artist <- str_replace_all(users_1month$artist, "Dick Haymes, Backup Vocals By Four Hits And A Miss", "Dick Haymes")
users_1month$artist <- str_replace_all(users_1month$artist, "Different Gear Vs. Sia", "Sia") #different gear not present in dataset, sia is
users_1month$artist <- str_replace_all(users_1month$artist, "Diktatûra", "Diktatura")
users_1month$artist <- str_replace_all(users_1month$artist, "Dim Chris. French Kiss \\(Origi", "Dim Chris")
users_1month$artist <- str_replace_all(users_1month$artist, "Diplo Featuring Rye Rye", "Diplo Feat. Rye Rye")
users_1month$artist <- str_replace_all(users_1month$artist, "Disco Polo \\-", "Disco Polo")
users_1month$artist <- str_replace_all(users_1month$artist, "Disney \\- Aladdin", "Disney")
users_1month$artist <- str_replace_all(users_1month$artist, "\\[Disney\\]", "Disney")
users_1month$artist <- str_replace_all(users_1month$artist, "Disney Channel Stars", "Disney")
users_1month$artist <- str_replace_all(users_1month$artist, "Dizzy Gillespie Jazzmen, Charlie Parker, Lucky Thompson, George Handy, Arvin Garrison, Ray Brown", "Dizzy Gillespie Sextet")
users_1month$artist <- str_replace_all(users_1month$artist, "Dj Bobo, E\\-Rotic, Fun Factory, Masterboy, Mr. President, Scooter, U96 And Worlds Apart", "Dj Bobo")
users_1month$artist <- str_replace_all(users_1month$artist, "Dj K\\-Tel", "Elektromeister Dj K\\-Tel")
users_1month$artist <- str_replace_all(users_1month$artist, "Dj Tomek ,Krs One,Torch\\&Rene \\-", "Dj Tomekk")
users_1month$artist <- str_replace_all(users_1month$artist, "Doc Watson\\/Earl Scruggs\\/Ricky Skaggs", "Doc Watson")
users_1month$artist <- str_replace_all(users_1month$artist, "Doctor Ross \\& His Jump \\& Jive Boys", "Doctor Ross")
users_1month$artist <- str_replace_all(users_1month$artist, "Doe Maar \\@ 4Uonly.Biz", "Doe Maar")
users_1month$artist <- str_replace_all(users_1month$artist, "Dusty Springfield \\- Son Of A Preacher Man", "Dusty Springfield")
users_1month$artist <- str_replace_all(users_1month$artist, "Dutch Masters", "Dutch Master")
users_1month$artist <- str_replace_all(users_1month$artist, "Elton John \\(Lion King\\)", "Elton John")
users_1month$artist <- str_replace_all(users_1month$artist, "Erol Alkan, A\\-Trak", "Erol Alkan \\& A\\-Trak")
users_1month$artist <- str_replace_all(users_1month$artist, "Everlast Feat Mobb Deep", "Everlast \\& Mobb Deep")
users_1month$artist <- str_replace_all(users_1month$artist, "Ewan Mcgregor\\/Nicole Kidman", "Ewan Mcgregor \\& Nicole Kidman")
users_1month$artist <- str_replace_all(users_1month$artist, "Nicole Kidman \\& Ewan Mcgregor", "Ewan Mcgregor \\& Nicole Kidman")
users_1month$artist <- str_replace_all(users_1month$artist, "Fertil Ground", "Fertile Ground")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Vii Advent Children", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Viii Piano Collections", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Vii Piano Collections", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy V \\~ 5\\+1", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Xi Vision Of Jiraat Ost", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Vii Reunion Tracks", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Anthology", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Ix Piano Collections", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Iv Piano Collections", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy X\\-2 Vocal Collection Paine", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Iv Celtic Moon", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy I \\& Ii", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Vi Stars Vol. 2", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Vi Piano Collections", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Anthology", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy S Generation", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Final Fantasy Vi Orchestral", "Final Fantasy")
users_1month$artist <- str_replace_all(users_1month$artist, "Fleet Foxes \\- White Winter Hymnal", "Fleet Foxes")
users_1month$artist <- str_replace_all(users_1month$artist, "Flo Rider Ft. T\\-Pain", "Flo Rida Ft. T\\-Pain")
users_1month$artist <- str_replace_all(users_1month$artist, "Frank Sinatra\\;Tommy Dorsey \\& His Orchestra\\;The Pied Pipers", "Frank Sinatra \\& The Tommy Dorsey Orchestra")
users_1month$artist <- str_replace_all(users_1month$artist, "Freshkills \\(Remix\\)", "Freshkills")
users_1month$artist <- str_replace_all(users_1month$artist, "God Help The Girl \\(Stuart Murdoch\\)\\/God Help The Girl \\(Stuart Murdoch\\)", "God Help The Girl")
users_1month$artist <- str_replace_all(users_1month$artist, "Gundam 00 Another Story \\[Mission-2306\\]", "Gundam")
users_1month$artist <- str_replace_all(users_1month$artist, "Hank Williams Sr, Jr, Iii", "Hank Williams, Hank Williams Jr., Hank Williams Iii")
users_1month$artist <- str_replace_all(users_1month$artist, "Hardal Www.RockDisneyDisneydDisneyr.Com", "Hardal")
users_1month$artist <- str_replace_all(users_1month$artist, "Jamie Long\\/Horse Shoes", "Jamie Long")
users_1month$artist <- str_replace_all(users_1month$artist, "Jamie Long\\/Cut The Red Wire", "Jamie Long")
users_1month$artist <- str_replace_all(users_1month$artist, "Jamie Long\\/The Sound Of Arrows", "Jamie Long")
users_1month$artist <- str_replace_all(users_1month$artist, "John Foxx \\+ Harold Budd", "John Foxx \\& Harold Budd")
users_1month$artist <- str_replace_all(users_1month$artist, "Jokke \\& Valentinerne Med Tourettes", "Jokke Med Tourettes")
users_1month$artist <- str_replace_all(users_1month$artist, "Joseph Arthur \\- Killer'S Knife", "Joseph Arthur")
users_1month$artist <- str_replace_all(users_1month$artist, "Joseph Arthur \\- Temporary People", "Joseph Arthur")
users_1month$artist <- str_replace_all(users_1month$artist, "Kane \\- Rain Down On Me \\(Tiesto Remix\\)", "Kane")
users_1month$artist <- str_replace_all(users_1month$artist, "Lady Gaga \\(Feat. Colby O'Donis\\)", "Lady Gaga")
users_1month$artist <- str_replace_all(users_1month$artist, "Lamont", "Lamont Dozier")
users_1month$artist <- str_replace_all(users_1month$artist, "Lanzamientosmp3 & Mixermusic", "Lanzamientosmp3.Es")
users_1month$artist <- str_replace_all(users_1month$artist, "Lars Winnerbäck Och Hovet", "Lars Winnerbäck")
users_1month$artist <- str_replace_all(users_1month$artist, "Le Quattro Stagioni", "Le Quattro Stagioni \\- Summer, Allegro Non Molto")
users_1month$artist <- str_replace_all(users_1month$artist, "Lifelike \\& Kris Menace \\- Patrick Hagenaar \\- Emanuel, Mccall \\& Jamesie Feat. Rita Campbell", "Lifelike \\& Kris Menace")
users_1month$artist <- str_replace_all(users_1month$artist, "Lil Mama Featuring T\\-Pain \\& Chris Brown", "Lil Mama Feat. Chris Brown \\& T\\-Pain")
users_1month$artist <- str_replace_all(users_1month$artist, "Linkin Park\\[Remixed By Bryan Aimetti\\]", "Linkin Park")
users_1month$artist <- str_replace_all(users_1month$artist, "Lord Finesse, Kid Capri\\-Gorill", "Lord Finesse")
users_1month$artist <- str_replace_all(users_1month$artist, "Lord Finesse, Ag, Diamond, Mar", "Lord Finesse")
users_1month$artist <- str_replace_all(users_1month$artist, "Lord Finesse, Akinyele\\-Gorilla", "Lord Finesse")
users_1month$artist <- str_replace_all(users_1month$artist, "Lord Finesse, Mc Lyte\\-Gorillar", "Lord Finesse")
users_1month$artist <- str_replace_all(users_1month$artist, "Lord Finesse, O.C.\\-Gorillarms", "Lord Finesse")
users_1month$artist <- str_replace_all(users_1month$artist, "Lord Finesse, Doo\\-Wop\\-Gorillar", "Lord Finesse")
users_1month$artist <- str_replace_all(users_1month$artist, "Louis Armstrong \\& His All\\-Stars", "Louis Armstrong \\& His Orchestra")
users_1month$artist <- str_replace_all(users_1month$artist, "Ltj Bukem Featuring Mc Conrad", "Ltj Bukem")
users_1month$artist <- str_replace_all(users_1month$artist, "Ludachrist", "Ludacris")
users_1month$artist <- str_replace_all(users_1month$artist, "Luis Bacalov \\- The Grand Duel", "Luis Bacalov")
users_1month$artist <- str_replace_all(users_1month$artist, "M 'N' M'S", "M \\& M")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥安室奈美恵", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Lisa", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Akiko Wada", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥日之内エミ \\& Ryohei", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥野宮真貴 \\& Crazy Ken Band", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Emyli \\& Yoshika", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Melody. \\& Ryohei", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo Loves Kahimi Karie", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo Loves Monday満ちる", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Bennie K", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "Ram Rider,倖田來未,Mink M\\-Flo Loves Doping Panda", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Rie Fu", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo Loves 加藤ミリヤ", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Sowelu", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Whee Sung", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo♥Bonnie Pink", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M\\-Flo Loves Doping Panda", "M\\-Flo")
users_1month$artist <- str_replace_all(users_1month$artist, "M.A.N.D.Y. Vs Booka Shade Feat. Laurie Anderson", "M.A.N.D.Y. Vs. Booka Shade Feat. Laurie Anderson")
users_1month$artist <- str_replace_all(users_1month$artist, "Madonna Ft. Justin \\& Timbaland", "Madonna")
users_1month$artist <- str_replace_all(users_1month$artist, "Madonna Ft. Justin Timberlake", "Madonna")
users_1month$artist <- str_replace_all(users_1month$artist, "Madonna Feat. Justin Timberlak", "Madonna")
users_1month$artist <- str_replace_all(users_1month$artist, "Mahala Raï Banda", "Mahala Rai Banda")
users_1month$artist <- str_replace_all(users_1month$artist, "Shantel Vs. Mahala Raï Banda", "Mahala Rai Banda Vs. Shantel")
users_1month$artist <- str_replace_all(users_1month$artist, "Manic Street Preachers Ft. Nina Persson \\(The Cardigans\\)", "Manic Street Preachers Featuring Nina Persson")
users_1month$artist <- str_replace_all(users_1month$artist, "Marco Demark Ft. Casey Barnes", "Marco Demark Feat Casey")
users_1month$artist <- str_replace_all(users_1month$artist, "Marco Demark Feat. Casey Barnes", "Marco Demark Feat Casey")
users_1month$artist <- str_replace_all(users_1month$artist, "Marco Demark Feat. Peter Millwood", "Marco Demark \\& Peter Millwood")
users_1month$artist <- str_replace_all(users_1month$artist, "Mariah Carey \\(With Cam'Ron\\)", "Mariah Carey")
users_1month$artist <- str_replace_all(users_1month$artist, "Masada String Trio", "Masada")
users_1month$artist <- str_replace_all(users_1month$artist, "Matt Caseli And Aston Martinez", "Matt Caseli \\& Aston Martinez")
users_1month$artist <- str_replace_all(users_1month$artist, "Matt Darey'S Mash Up Feat. Mar", "Matt Darey'S Mash Up Feat. Marcella")
users_1month$artist <- str_replace_all(users_1month$artist, "Mauro Picott", "Mauro Picotto")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom \\& Mf Grimm", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom And Dangermouse \\[The Mouse \\& The Mask\\]", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom With Count Bass\\-D", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom With Mr. Fantastik", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom With Angelika And 4 Ize", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom \\[The Very Best Of Mf Doom Cd3\\]", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom \\& Hassan Chop \\[Live 2006\\]", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom Madvillian \\[Koushik Remixes\\]", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom, Rza \\& Think Differently Music", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom As Viktor Vaughn \\[Mr Clean\\]", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom \\& Trunks", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "Mf Doom And Dangermouse \\[The Mouse \\& The Mask\\]", "Mf Doom")
users_1month$artist <- str_replace_all(users_1month$artist, "\\(Remix: Soulwax\\)", "")
users_1month$artist <- str_replace_all(users_1month$artist, "Michael Giacchino \\- Medal Of Honor", "Michael Giacchino")
users_1month$artist <- str_replace_all(users_1month$artist, "Mos Def Pharoahe Monch Nate Dogg", "Mos Def")
users_1month$artist <- str_replace_all(users_1month$artist, "Nelson Riddle \\& His Orchestra \\- Lolita  \\- O.S.T.", "Nelson Riddle And His Orchestra")
users_1month$artist <- str_replace_all(users_1month$artist, "Oakenfold Feat Pharrell Williams \\+ Tom Novy \\& Lima", "Oakenfold Ft Pharrell Williams")
users_1month$artist <- str_replace_all(users_1month$artist, "Paul Oakenfold Ft. Pharrel Williams", "Oakenfold Ft Pharrell Williams")
users_1month$artist <- str_replace_all(users_1month$artist, "Offer Nissim Feat. Maya", "Offer Nissim Feat Maya")
users_1month$artist <- str_replace_all(users_1month$artist, "Offer Nissim Featuring Maya", "Offer Nissim Feat Maya")
users_1month$artist <- str_replace_all(users_1month$artist, "Offer Nissim Feat. Maya Vs. Chanc", "Offer Nissim Feat Maya")
users_1month$artist <- str_replace_all(users_1month$artist, "Okkervil River \\- Lost Coastlines", "Okkervil River")
users_1month$artist <- str_replace_all(users_1month$artist, "Olivia Newton\\-John \\& Electric Light Orchestra", "Olivia Newton\\-John, Electric Light Orchestra")
users_1month$artist <- str_replace_all(users_1month$artist, "Paramore   \\(Estados Unidos\\)", "Paramore")
users_1month$artist <- str_replace_all(users_1month$artist, "Paul Whiteman And His Orchestra \\(Vocal Jack Teagarden\\)", "Paul Whiteman \\& His Orchestra")
users_1month$artist <- str_replace_all(users_1month$artist, "Pitbull Feat. Lil' Jon", "Pitbull Feat. Lil Jon")
users_1month$artist <- str_replace_all(users_1month$artist, "Pitbull Feat Lil Jon", "Pitbull Feat. Lil Jon")
users_1month$artist <- str_replace_all(users_1month$artist, "Placebo \\(Feat. David Bowie\\)", "Placebo \\& David Bowie")
users_1month$artist <- str_replace_all(users_1month$artist, "Ram Rider,倖田來未,Mink M\\-Flo Loves Doping Panda", "Ram Rider")
users_1month$artist <- str_replace_all(users_1month$artist, "Ramsey Lewis \\- The 'In' Crowd", "Ramsey Lewis")
users_1month$artist <- str_replace_all(users_1month$artist, "Red Letter Day \\(90'S Indiepop \\)", "Red Letter Day")
users_1month$artist <- str_replace_all(users_1month$artist, "Red Letter Day \\(80'S Power Pop\\)", "Red Letter Day")
users_1month$artist <- str_replace_all(users_1month$artist, "Seraphim Shock \\- Halloween, Sex N' Vegas", "Seraphim Shock")
users_1month$artist <- str_replace_all(users_1month$artist, "Sesto Senteo", "Sesto Sento")
users_1month$artist <- str_replace_all(users_1month$artist, "Silent Hill 2 Cst", "Silent Hill")
users_1month$artist <- str_replace_all(users_1month$artist, "Silent Hill 3 Cst", "Silent Hill")
users_1month$artist <- str_replace_all(users_1month$artist, "Silent Hill 2\\- Complete \\- Disc 02 \\- Extras", "Silent Hill")
users_1month$artist <- str_replace_all(users_1month$artist, "Skream \\(Tease Cay'S Cray \\- Fat Freddy'S Drop \\(Mala Remix\\)", "Skream")
users_1month$artist <- str_replace_all(users_1month$artist, "Steve Angello, Axwell, Sebastian Ingrosso, Laidback Luke", "Axwell, Sebastian Ingrosso, Steve Angello \\& Laidback Luke")
users_1month$artist <- str_replace_all(users_1month$artist, "Steve Angello, Sebastian Ingrosso, Axwell \\& Laidback Luke", "Axwell, Sebastian Ingrosso, Steve Angello \\& Laidback Luke")
users_1month$artist <- str_replace_all(users_1month$artist, "Tha Playah Vs. Evil Activities", "Tha Playah Vs Evil Activities")
users_1month$artist <- str_replace_all(users_1month$artist, "The Blackout All Stars", "The Blackout Allstars")
users_1month$artist <- str_replace_all(users_1month$artist, "Ultra Dj'S", "Ultra Djs")
users_1month$artist <- str_replace_all(users_1month$artist, "Vnv Nation \\- Advance And Follow \\(V2\\) \\(2001\\)", "Vnv Nation")
users_1month$artist <- str_replace_all(users_1month$artist, "Vnv Nation \\- Standing-Burning Empires \\(2 Cd\\) \\(2000\\)", "Vnv Nation")
users_1month$artist <- str_replace_all(users_1month$artist, "Waterpistols \\& Daisy Feat. Łozo", "Waterpistols \\& Daisy Feat Łozo")
users_1month$artist <- str_replace_all(users_1month$artist, "Yeah Yeah Yeahs                     \\- Www.Netosdesalim.Com.Br", "Yeah Yeah Yeahs")


# veel djs met NA labeltype, wat ook logisch is want dit zijn vaak meer zolderkamer artiesten. verder ook veel orkesten met NA


# write to csv
write.csv(users_1month, file = "../../gen/temp/users_1month.csv")
