library(data.table)
library(dplyr)
library(lubridate)
library(stringr)

#load data
userdata_1k <- fread("../../data/userdata_1k.csv")

#remove columns 
userdata_1k <- userdata_1k[, -1]

###################
#DATE MANIPULATION#
###################

# timestamp to dates
userdata_1k$date <- as.Date(userdata_1k$timestamp)

# dates to total time timestamps
userdata_1k <- userdata_1k %>% group_by(userid) %>% mutate(total_days = max(date)-min(date))

# days numeric
userdata_1k$total_days_num <- as.numeric(userdata_1k$total_days, unit = "days")

# months numeric
userdata_1k$months <- time_length(userdata_1k$total_days, unit = "months")

# rearrange colums
userdata_1k <- userdata_1k[, c(1, 2, 7:10, 3:6)]

#################
#FILTER 1 MONTHS#
#################

userdata_1k_1month <- userdata_1k %>% filter(months >= 1)

#####################
#DETERMINE DATERANGE#
#####################

# check for users with 1 months total listening time
users_1m <- userdata_1k_1month %>% filter(months < 2)
users_1m <- users_1m %>% group_by(userid) %>% mutate(mindate = min(date))
users_1m <- users_1m %>% group_by(userid) %>% mutate(maxdate = max(date))

table(users_1m$mindate)
table(users_1m$maxdate)
# So, the minimum dates are ranging all in the March 2009. Max dates are all in May 2009, except one who is in the end of April 2009. 
# Conclusion: dataset in April 2009 as this is a month where all have listened

# remove dataset for clean environment
rm(users_1m, userdata_1k_1month)

##################
#FILTER DATERANGE#
##################

users_1month <- userdata_1k %>% filter(date >= "2009-04-01" & date <= "2009-04-30")

###############
#CLEAN ARTISTS#
###############
artist_subset <- users_1month[, 8] %>% distinct()

artist_subset$artist <- str_replace_all(artist_subset$artist, "[:digit:][:digit:]\\. Kaliyuga Pro.", "Kaliyuga Pro.")
artist_subset$artist <- str_replace_all(artist_subset$artist, ",  Melodie", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "/Melodie", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "- Ost Cd 1", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "- Ost Cd 2", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "2paq", "2pac")
artist_subset$artist <- str_replace_all(artist_subset$artist, "8 Mile Soundtrack - ", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Act One", "Act 1")
artist_subset$artist <- str_replace_all(artist_subset$artist, " \\(1988\\)", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Afro Menduesa", "Afro Medusa")
artist_subset$artist <- str_replace_all(artist_subset$artist, "0Akon", "Akon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Akon Feat Lil Wayne", "Akon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Akon Ft. Lil Wayne", "Akon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Akon Featuring Eminem", "Akon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Akon Feat Colby O'Donis & Kardinal Offishall", "Akon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Albert King With Stevie Ray Vaughan", "Albert King")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Albert King & Otis Rush", "Albert King")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Alex Gaudino Feat. Shena", "Alex Gaudino")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ali Farka Touré With Ry Cooder", "Ali Farka Touré")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ali Farka Touré & Toumani Diabaté", "Ali Farka Touré")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Allen Ginsberg / Illyb", "Allen Ginsberg")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Allison Crowe", "Allison Crowe (Holiday)")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Alozade And Hollow Point", "Alozade")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Alpha Beat", "Alphabeat")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Altamiro Carrilho & Ronaldo Do Bandolim", "Altamiro")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Alva Noto + Ryuichi Sakamoto", "Alva Noto")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Alva Noto + Opiate", "Alva Noto")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Amanda Seyfried, Ashley Lilley And Rachel Mcdowall", "Amanda Seyfried")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Amanda Seyfried/Dominic Cooper", "Amanda Seyfried")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dominic Cooper And Amanda Seyfried", "Amanda Seyfried")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Amel Larrieux, Glenn Lewis, Stanley Clarke", "Amel Larrieux")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Amerie Feat.  Fabolous", "Amerie")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Amilcare Poncielli", "Amilcare Ponchielli")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Andrea Demirović", "Andrea Demirovic")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Andrew Spencer Vs. Lazard", "Andrew Spencer") # check if lazard niet label 1 is
artist_subset$artist <- str_replace_all(artist_subset$artist, "Andrew W.K. & B-Roc", "Andrew W.K.")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Andy Hunter", "Andy Hunter°")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Andy Sheppard & Naná Vasconcelos", "Andy Sheppard")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Angelo Badalamenti - Laura'S Theme (Instrumental)", "Angelo Badalamenti")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Anna Maria Jopek + Tomasz Stanko", "Anna Maria Jopek") # check tomasz stanko
artist_subset$artist <- str_replace_all(artist_subset$artist, "Antoine Clamaran Feat. Emily Chick[Www.Zabawa.Org]", "Antoine Clamaran")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Antoine Clamaran & Emily Chick", "Antoine Clamaran")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Apocalyptica Feat Three Days Grace", "Apocalyptica")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Apocalyptica Feat. A. Gontier", "Apocalyptica")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Armin Van Buuren (Feat. Sharon Den Adel)", "Armin Van Buuren")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Armin Van Buuren & Dj Shah (Feat. Chris Jones)", "Armin Van Buuren")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Armin Van Buuren Feat. Sharon Den Adel", "Armin Van Buuren")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Armin Van Buuren F. Ray Wilson", "Armin Van Buuren")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Armin Van Buuren Feat. Jan Vayne", "Armin Van Buuren")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Armin Van Buuren Featuring Ray Wilson", "Armin Van Buuren")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Axwell (By @Ello-)", "Axwell")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Axwell Vs. Kanye West", "Axwell")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Az Rotator", "Az-Rotator")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Baden Powell-Charlie Byrd-Joao Gilberto", "Baden Powell/Charlie Byrd/Joao Gilberto")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Beat Konducta (Aka Madlib)", "Beat Konducta")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Beyoncй", "Beyoncé")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Birdman & Lil' Wayne", "Birdman & Lil Wayne")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Bmx Bandits [With Yeon Gene]", "Bmx Bandits")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Booker T. & The Mgs - Green Onions", "Booker T. & The Mgs")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Bournemouth Symphony Orchestra/Bournemouth Symphony Orchestra", "Bournemouth Symphony Orchestra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Brandy -[Emb]-", "Brandy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Bruce Hornsby Feat. Sting", "Bruce Hornsby & Sting")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Buck 65 Remix (Featuring Sufjan Stevens And Serengeti)", "Buck 65")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Buck 65 Remix (Featuring Sufjan Stevens)", "Buck 65")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Butti 49", "Butti-49")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Carter Burwell/Various Artist", "Carter Burwell") 
artist_subset$artist <- str_replace_all(artist_subset$artist, "Cavaleiros Do Zodíaco", "Cavaleiros Do Zodiaco")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Www.Cavaleiroszodiaco.Com.Br", "Cavaleiros Do Zodiaco")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Os Cavaleiros Do Zodiaco", "Cavaleiros Do Zodiaco")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Centro-Matic South San Gabriele", "Cavaleiros Do Zodiaco") #south san gabriele is an album of cavaleiros do Zodiaco
artist_subset$artist <- str_replace_all(artist_subset$artist, "Cevin Fisher Feat. Loletta Holloway", "Cevin Fisher Feat. Loleatta Holloway")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Chick Corea Elektric Band Ii", "Chick Corea Elektric Band")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Chris Montana Pres Bora Bora C", "Chris Montana Pres Bora Bora Chicks")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Chris Tomlin, Martin Smith, Kirk Franklin And Watoto Children'S Choir", "Chris Tomlin")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Christian Prommer'S Drum Lesson", "Christian Prommer'S Drumlesson")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Christina Aguilera, Mya, Pink, Lil Kim", "Christina Aguilera, Mya, Pink & Lil' Kim")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Christina Aguilera, Lil' Kim, Mýa & P!Nk", "Christina Aguilera, Mya, Pink & Lil' Kim")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ciara Featuring Justin Timberlake", "Ciara Ft. Justin Timberlake")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ciara Feat Justin Timberlake", "Ciara Ft. Justin Timberlake")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Cloud Cult - The Ghost Inside Our House", "Cloud Cult") # song of Cloud Cult
artist_subset$artist <- str_replace_all(artist_subset$artist, "Coco Tea", "Cocoa Tea")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Code Geass Lelouch Of The Rebellion O.S.T. 2", "Code Geass Lelouch Of The Rebellion O.S.T.")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Code Geass Lelouch Of The Rebellion R2 O.S.T. 2", "Code Geass Lelouch Of The Rebellion O.S.T.")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Code Geass Lelouch Of The Rebellion R2 O.S.T. 1", "Code Geass Lelouch Of The Rebellion O.S.T.")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Cold (Metal)", "Cold")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Coldplay + Weezer + Cut Copy + The Blow + M.I.A. + Reading Rainbow", "Coldplay")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Cut Chemist Meets Shortkut", "Cut Chemist/Shortcut")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Daddy Dj - Let Your Body Talk", "Daddy Dj")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Daft Punk Vs. U2", "Daft Punk")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Daft Punk Vs B.Benassi", "Daft Punk")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dahlbäck, Diaz, Young Rebels & Terri B", "Dahlbäck, Diaz & Young Rebels Ft. Terri B!")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dahlbäck, Diaz & Young Rebels Feat. Terri B!", "Dahlbäck, Diaz & Young Rebels Ft. Terri B!")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Damien Jurado & Gathered In Song", "Damien Jurado")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Damien Rice - B-Sides", "Damien Rice")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dana Fuchs, Evan Rachel Wood, Jim Sturgess, Joe Anderson & T.V. Carpio", "Dana Fuchs, Jim Sturgess, Evan Rachel Wood And T. V. Carpio")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Danny Dove & Steve Smart Ft Amanda Wilson", "Danny Dove & Steve Smart (Feat. Amanda Wilson)")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Darude Feat. Blake Lewis", "Darude Ft. Blake Lewis")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dave Aude & Tall Paul Featuring Sisely Treasure", "Dave Aude & Tall Paul Ft. Sisely Treasure")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dave Dean 'S Musical Forklift", "Dave Dean'S Musical Forklift")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Carradine, Julie Dreyfus And Uma Thurman", "Uma Thurman, David Carradine & Julie Dreyfus")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Guetta, Steve Angello, Joachim Garraud, Sebastian Ingrosso, Chris Willis", "David Guetta")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Morales Presents The Face Ft. Juliet Roberts", "David Morales")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Morales Feat. Lea-Lorien", "David Morales")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Sylvian, Ryuichi Sakamoto, Amadeo Pace, Keigo Oyamada & Sketch Show", "David Sylvian")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Torn, Tim Berne, Craig Taborn, Tom Rainey", "David Torn")
artist_subset$artist <- str_replace_all(artist_subset$artist, "David Vandervelde - Hit The Road", "David Vandervelde")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Daz-I-Kue", "Daz-I-Cue")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Db Boulebard", "Db Boulevard")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dean Martin, Frank Sinatra, Sa", "Dean Martin & Frank Sinatra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dear Nora & Casiotone For The Painfully Alone", "Dear Nora")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Death Note Ost I", "Death Note")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Death Note Ost Ii", "Death Note")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Death Note Ost Iii", "Death Note")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Del The Funky Homosapien", "Del Tha Funkee Homosapien/Gorillaz")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Delinquent & Kcat", "Delinquent (Feat. Kcat)")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Delly Ranx", "Delly Ranks")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Demarco- When The Love A Come Down", "Demarco")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Detroit Grand Pubahs/New Order", "Detroit Grand Pubahs")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dick Haymes, Backup Vocals By Four Hits And A Miss", "Dick Haymes")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Different Gear Vs. Sia", "Sia") #different gear not present in dataset, sia is
artist_subset$artist <- str_replace_all(artist_subset$artist, "Diktatûra", "Diktatura")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dim Chris. French Kiss (Origi", "Dim Chris")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Diplo Featuring Rye Rye", "Diplo Feat. Rye Rye")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Disco Polo -", "Disco Polo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Disney - Aladdin", "Disney")
artist_subset$artist <- str_replace_all(artist_subset$artist, "[Disney]", "Disney")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Disney Channel Stars", "Disney")
# ff zoeken op ost en dat miss weg
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dizzy Gillespie Jazzmen, Charlie Parker, Lucky Thompson, George Handy, Arvin Garrison, Ray Brown", "Dizzy Gillespie Sextet")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dj Bobo, E-Rotic, Fun Factory, Masterboy, Mr. President, Scooter, U96 And Worlds Apart", "Dj Bobo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dj K-Tel", "Elektromeister Dj K-Tel")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dj Tomek ,Krs One,Torch&Rene -", "Dj Tomekk")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Doc Watson/Earl Scruggs/Ricky Skaggs", "Doc Watson")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Doctor Ross & His Jump & Jive Boys", "Doctor Ross")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Doe Maar @ 4Uonly.Biz", "Doe Maar")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dusty Springfield - Son Of A Preacher Man", "Dusty Springfield")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Dutch Masters", "Dutch Master")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Elton John (Lion King)", "Elton John")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Erol Alkan, A-Trak", "Erol Alkan & A-Trak")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Everlast Feat Mobb Deep", "Everlast & Mobb Deep")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ewan Mcgregor/Nicole Kidman", "Ewan Mcgregor & Nicole Kidman")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Nicole Kidman & Ewan Mcgregor", "Ewan Mcgregor & Nicole Kidman")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Fertil Ground", "Fertile Ground")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Vii Advent Children", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Viii Piano Collections", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy V ~ 5+1", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Xi Vision Of Jiraat Ost", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Vii Reunion Tracks", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Anthology", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Ix Piano Collections", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Iv Piano Collections", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy X-2 Vocal Collection Paine", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Iv Celtic Moon", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy I & Ii", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Vi Stars Vol. 2", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Vi Piano Collections", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Anthology", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy S Generation", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Final Fantasy Vi Orchestral", "Final Fantasy")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Fleet Foxes - White Winter Hymnal", "Fleet Foxes")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Flo Rider Ft. T-Pain", "Flo Rida Ft. T-Pain")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Frank Sinatra;Tommy Dorsey & His Orchestra;The Pied Pipers", "Frank Sinatra & The Tommy Dorsey Orchestra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Freshkills (Remix)", "Freshkills")
artist_subset$artist <- str_replace_all(artist_subset$artist, "God Help The Girl (Stuart Murdoch)/God Help The Girl (Stuart Murdoch)", "God Help The Girl")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Gundam 00 Another Story [Mission-2306]", "Gundam")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Hank Williams Sr, Jr, Iii", "Hank Williams, Hank Williams Jr., Hank Williams Iii")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Hardal Www.RockDisneyDisneydDisneyr.Com", "Hardal")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Jamie Long/Horse Shoes", "Jamie Long")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Jamie Long/Cut The Red Wire", "Jamie Long")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Jamie Long/The Sound Of Arrows", "Jamie Long")
artist_subset$artist <- str_replace_all(artist_subset$artist, "John Foxx + Harold Budd", "John Foxx & Harold Budd")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Jokke & Valentinerne Med Tourettes", "Jokke Med Tourettes")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Joseph Arthur - Killer'S Knife", "Joseph Arthur")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Joseph Arthur - Temporary People", "Joseph Arthur")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Kane - Rain Down On Me (Tiesto Remix)", "Kane")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lady Gaga (Feat. Colby O'Donis)", "Lady Gaga")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lamont", "Lamont Dozier")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lanzamientosmp3 & Mixermusic", "Lanzamientosmp3.Es")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lars Winnerbäck Och Hovet", "Lars Winnerbäck")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Le Quattro Stagioni", "Le Quattro Stagioni - Summer, Allegro Non Molto")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lifelike & Kris Menace - Patrick Hagenaar - Emanuel, Mccall & Jamesie Feat. Rita Campbell", "Lifelike & Kris Menace")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lil Mama Featuring T-Pain & Chris Brown", "Lil Mama Feat. Chris Brown & T-Pain")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Linkin Park[Remixed By Bryan Aimetti]", "Linkin Park")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lord Finesse, Kid Capri-Gorill", "Lord Finesse")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lord Finesse, Ag, Diamond, Mar", "Lord Finesse")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lord Finesse, Akinyele-Gorilla", "Lord Finesse")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lord Finesse, Mc Lyte-Gorillar", "Lord Finesse")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lord Finesse, O.C.-Gorillarms", "Lord Finesse")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Lord Finesse, Doo-Wop-Gorillar", "Lord Finesse")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Louis Armstrong & His All-Stars", "Louis Armstrong & His Orchestra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ltj Bukem Featuring Mc Conrad", "Ltj Bukem")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ludachrist", "Ludacris")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Luis Bacalov - The Grand Duel", "Luis Bacalov")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M 'N' M'S", "M & M")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥安室奈美恵", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Lisa", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Akiko Wada", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥日之内エミ & Ryohei", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥野宮真貴 & Crazy Ken Band", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Emyli & Yoshika", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Melody. & Ryohei", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo Loves Kahimi Karie", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo Loves Monday満ちる", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Bennie K", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ram Rider,倖田來未,Mink M-Flo Loves Doping Panda", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Rie Fu", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo Loves 加藤ミリヤ", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Sowelu", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Whee Sung", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo♥Bonnie Pink", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M-Flo Loves Doping Panda", "M-Flo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "M.A.N.D.Y. Vs Booka Shade Feat. Laurie Anderson", "M.A.N.D.Y. Vs. Booka Shade Feat. Laurie Anderson")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Madonna Ft. Justin & Timbaland", "Madonna")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Madonna Ft. Justin Timberlake", "Madonna")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Madonna Feat. Justin Timberlak", "Madonna")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mahala Raï Banda", "Mahala Rai Banda")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Shantel Vs. Mahala Raï Banda", "Mahala Rai Banda Vs. Shantel")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Manic Street Preachers Ft. Nina Persson (The Cardigans)", "Manic Street Preachers Featuring Nina Persson")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Marco Demark Ft. Casey Barnes", "Marco Demark Feat Casey")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Marco Demark Feat. Casey Barnes", "Marco Demark Feat Casey")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Marco Demark Feat. Peter Millwood", "Marco Demark & Peter Millwood")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mariah Carey (With Cam'Ron)", "Mariah Carey")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Masada String Trio", "Masada")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Matt Caseli And Aston Martinez", "Matt Caseli & Aston Martinez")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Matt Darey'S Mash Up Feat. Mar", "Matt Darey'S Mash Up Feat. Marcella")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mauro Picott", "Mauro Picotto")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom & Mf Grimm", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom And Dangermouse [The Mouse & The Mask]", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom With Count Bass-D", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom With Mr. Fantastik", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom With Angelika And 4 Ize", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom [The Very Best Of Mf Doom Cd3]", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom & Hassan Chop [Live 2006]", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom Madvillian [Koushik Remixes]", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom, Rza & Think Differently Music", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom As Viktor Vaughn [Mr Clean]", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom & Trunks", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mf Doom And Dangermouse [The Mouse & The Mask]", "Mf Doom")
artist_subset$artist <- str_replace_all(artist_subset$artist, "\\(Remix: Soulwax\\)", "")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Michael Giacchino - Medal Of Honor", "Michael Giacchino")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Mos Def Pharoahe Monch Nate Dogg", "Mos Def")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Nelson Riddle & His Orchestra - Lolita  - O.S.T.", "Nelson Riddle And His Orchestra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Oakenfold Feat Pharrell Williams + Tom Novy & Lima", "Oakenfold Ft Pharrell Williams")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Paul Oakenfold Ft. Pharrel Williams", "Oakenfold Ft Pharrell Williams")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Offer Nissim Feat. Maya", "Offer Nissim Feat Maya")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Offer Nissim Featuring Maya", "Offer Nissim Feat Maya")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Offer Nissim Feat. Maya Vs. Chanc", "Offer Nissim Feat Maya")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Okkervil River - Lost Coastlines", "Okkervil River")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Olivia Newton-John & Electric Light Orchestra", "Olivia Newton-John, Electric Light Orchestra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Paramore   \\(Estados Unidos\\)", "Paramore")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Paul Whiteman And His Orchestra \\(Vocal Jack Teagarden\\)", "Paul Whiteman & His Orchestra")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Pitbull Feat. Lil' Jon", "Pitbull Feat. Lil Jon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Pitbull Feat Lil Jon", "Pitbull Feat. Lil Jon")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Placebo \\(Feat. David Bowie\\)", "Placebo & David Bowie")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ram Rider,倖田來未,Mink M-Flo Loves Doping Panda", "Ram Rider")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ramsey Lewis - The 'In' Crowd", "Ramsey Lewis")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Red Letter Day \\(90'S Indiepop \\)", "Red Letter Day")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Red Letter Day \\(80'S Power Pop\\)", "Red Letter Day")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Seraphim Shock - Halloween, Sex N' Vegas", "Seraphim Shock")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Sesto Senteo", "Sesto Sento")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Silent Hill 2 Cst", "Silent Hill")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Silent Hill 3 Cst", "Silent Hill")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Silent Hill 2- Complete - Disc 02 - Extras", "Silent Hill")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Skream (Tease Cay'S Cray - Fat Freddy'S Drop \\(Mala Remix\\)", "Skream")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Steve Angello, Axwell, Sebastian Ingrosso, Laidback Luke", "Axwell, Sebastian Ingrosso, Steve Angello & Laidback Luke")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Steve Angello, Sebastian Ingrosso, Axwell & Laidback Luke", "Axwell, Sebastian Ingrosso, Steve Angello & Laidback Luke")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Tha Playah Vs. Evil Activities", "Tha Playah Vs Evil Activities")
artist_subset$artist <- str_replace_all(artist_subset$artist, "The Blackout All Stars", "The Blackout Allstars")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Ultra Dj'S", "Ultra Djs")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Vnv Nation - Advance And Follow \\(V2\\) \\(2001\\)", "Vnv Nation")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Vnv Nation - Standing-Burning Empires \\(2 Cd\\) \\(2000\\)", "Vnv Nation")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Waterpistols & Daisy Feat. Łozo", "Waterpistols & Daisy Feat Łozo")
artist_subset$artist <- str_replace_all(artist_subset$artist, "Yeah Yeah Yeahs                     - Www.Netosdesalim.Com.Br", "Yeah Yeah Yeahs")




# bij 8051 gebleven
# featuring, vs. , vs, & , ft. , feat , / , , , and , - 
# veel djs met NA labeltype, wat ook logisch is want dit zijn vaak meer zolderkamer artiesten. verder ook veel orkesten met NA
# checken nicole kidman bij Ewan Mcgregor/Nicole Kidman


# write to csv
#write.csv(users_1month, file = "../../gen/temp/users_1month.csv")
